name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. (Optional) Run tests using pytest
      # Uncomment this step if you have tests. Otherwise, remove or comment it out.
      - name: Run tests
        run: |
          pytest

      # 5. Initialize or migrate the database
      - name: Initialize / Migrate Database
        run: |
          python -c "from app import init_db; init_db()"

      # 6. Trigger a deployment on Render via the API (optional if auto-deploy is enabled)
      - name: Trigger Render Deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}"
