name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run database initialization/migrations
      - name: Initialize / Migrate Database
        run: |
          # This calls the init_db function in your app.
          # Modify this if you use a more robust migration tool.
          python -c "from app import init_db; init_db()"

      # Optionally run tests
      - name: Run tests
        run: |
          # If you have tests, run them here (for example, using pytest)
          pytest

      # Deploy to Render
      # Option 1: If your Render service is linked to GitHub, simply pushing changes triggers a deploy.
      # Option 2: You can trigger a deploy using Render's API. For example:
      - name: Trigger Render Deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}"
